### ISSUE TITLE
Discuss matching more conventional ES module import standard

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-js-sdk#194]
The way we are currently doing module imports / exports (whatever) seems a bit confusing and doesn't match what may have emerged as a sort of convention (e.g. with Angular, and Ionic, for example).

```
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
```
versus...

```
import * as PersistedDocument from "carbonldp/PersistedDocument";
import * as Response from "carbonldp/HTTP/Response";
```

Let's discuss this. At a minimum, we need to clarify what we're doing better in the website documentation because it is currently very confusing for me to understand how to properly import modules.

**Comment by MiguelAraCo** [comment]
Unfortunately at the time we were designing the SDK, no convention had emerged for importing/exporting modules (ES modules were brand new). It is important to note that the way the SDK imports/exports isn't against the standard. `import * as` is a valid way of importing modules. 

Still, we are aware that the people are using named exports instead of default or `*` imports. We've been talking about how to restructure the SDK to match that but it requires a complete restructure.

@roddolf has been working on figuring our options to tackle this problem and some others that are related to it.

For the time being there's documentation about how we do this in the section:
"JavaScript SDK" > "Getting started" > "Installing the SDK"

Please take a look at that description and feel free to propose how we could improve it.

We'll keep working on the plans for restructuring the SDK, until then, documenting it and giving enough examples is the most we can do.

**Comment by MiguelAraCo** [comment]
Related problem: #161

**Comment by roddolf** [comment]
Since SDK version 5, the imports have been refactored to follow a closer version of the conventions.
For example:
```typescript
// From
import * as Response from "carbonldp/HTTP/Response";
// To
import { Response } from "carbonldp/HTTP/Response";
// Or the recommended
import { Response } from "carbonldp/HTTP";
```
