### ISSUE TITLE
Implement resend request when different content type

### ISSUE THREAD

**Issue by roddolf** [CarbonLDP/carbonldp-js-sdk#213]
If a content type of a request is different of the expected one, the SDK should resend it adding a no cache flag.

It is a common behavior, of browsers to cache a resource even if the accept header is different and adding the `Vary: Accept` header does not work.

**Comment by codyburleson** [comment]
This is the issue where the documentation leads you to validate installation by loading a page in the browser, which gets cached. Later, when you first open the workbench, there is an error, because the browser returns the resource from cache and in that case, it is in XML and not JSON-LD. So, if you hard-refresh the workbench, it removes the issue.
