### ISSUE TITLE
Unexpected interpretation of a @set property in subquery

### ISSUE THREAD

**Issue by Yahaire** [CarbonLDP/carbonldp-js-sdk#349]
I have a movie database with a container for movies and a container for persons. The persons appear as actors on the movies through an access point.

I tried to get all the resolved actors of a movie by using the `.$get()` method along with a subquery as such:
```typescript
const rawMovieResult = await this.carbonLDP.documents.$get(this.moviesURL + movieId + '/', _ => _
  .properties({
    'actor': {
      query: _ => _.properties(_.all)
    },
  })
);
```
The problem is that this is returning a movie object with **one** resolved actor, when I knew for certain that **four** actors should be returned. Adding the type of the container to the actor property actually solves this (Code below), but it seems weird that the SDK is interpretting the response as a single value property instead of an array of 4 elements.

Anyways, just wanted to point this out.

Working code:
```typescript
const rawMovieResult = await this.carbonLDP.documents.$get(this.moviesURL + movieId + '/', _ => _
  .properties({
    'actor': {
      "@container": "@set", // <--- Add this line!
      query: _ => _.properties(_.all)
    },
  })
);
```

**Comment by roddolf** [comment]
This behavior is by design, **every property** is interpreted as a **single value** until specified differently. This is because the properties specification is an extensión of the object schemas.

As you pointed out, to make it work you need to:
-  Directly specify the `"@container": "@set"` in the query, or
-  Specify the complete schema of your object: https://carbonldp.com/documentation/v5.x.x/javascript-sdk/object-schema/ (**recommended practice**).

**Comment by Yahaire** [comment]
I see. I guess I'll work on extending the object schema as you suggested. It'll probably be better than having to write the `@set` line every other method.

Thanks!
