### ISSUE TITLE
Modify documentation generator to create multiple pages

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-js-sdk#352]
Consider creating multiple pages instead of one big HTML to improve documentation performance (and potentially also search).

**Comment by roddolf** [comment]
Dgeni can create different output from every symbol in the sources (class/interface/type).
So making a more modular documentation would require extensive changes in the templates since there only exists a main template entry from where all the information is sent.

These templates where the ones used by the old documentation system (JSON descriptions in the tests), so the Dgeni building is re-processing the model that Dgeni already generates to work.
I would suggest to start over the templates with the desired design and use the models of Dgeni to avoid this re-doing and this would lead to fewer modifications if anything new is required to be added later on since information of the symbols can be extracted easier from the Dgeni's model.

**Comment by roddolf** [comment]
Closing in favor of #390, which will generate multiple pages.
