### ISSUE TITLE
.$removeMembers() gives Bad Request error in IE

### ISSUE THREAD

**Issue by Yahaire** [CarbonLDP/carbonldp-js-sdk#364]
I was trying to run `.$removeMembers` in Internet Explorer and the method always fails with the following error:
```
"BadRequestError"
"The attempt of parsing the request's body failed"
400
```

In the request body I see that the `DELETE` request is the one that's failing. I also notice that it has the following headers:
```
   Accept: application/ld+json
   Accept-Encoding: gzip, deflate
   Accept-Language: en-US
   Cache-Control: no-cache
   Connection: Keep-Alive
   Content-Length: 9
   Content-Type: text/plain; charset=UTF-8
   Host: honda-emi-carbon.lab.base22.com
   Origin: http://localhost:4200
   prefer: http://www.w3.org/ns/ldp#Container; rel=interaction-model, include="https://carbonldp.com/ns/v1/platform#PreferMembershipTriples", omit="https://carbonldp.com/ns/v1/platform#PreferMembershipResources https://carbonldp.com/ns/v1/platform#PreferContainmentTriples https://carbonldp.com/ns/v1/platform#PreferContainmentResources https://carbonldp.com/ns/v1/platform#PreferContainer"
   Referer: http://localhost:4200/authenticated/modules/users
   User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko
```

Lastly, it seems like the request is also sending the following body:
```undefined```

This is weird as the method works well in Firefox and Chrome.

**Comment by roddolf** [comment]
IE explorer has a problem that sending the `undefined` keyword, it is serialized.

But nevertheless, this behavior is not raized by the SDK, since it will never send anything if the body is a falsy value.

You need to check if in your project there isn't anything that is messing up with the request.
To fix the issue with IE you can not send anything or send `null` instead of the `undefined`.
